
# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2023.2.307
# Date: 2024-09-02 17:44

# Copyright (C) 2013 - 2023 Efinix Inc. All rights reserved.

# Device: T120F324
# Project: sha_uart_v1
# Timing Model: C4 (final)

# PLL Constraints
#################
create_clock -period 100.0000 clk

# GPIO Constraints
####################
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {i_uart_rx}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {i_uart_rx}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {rst}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {rst}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_uart_tx}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_uart_tx}]

# LVDS RX GPIO Constraints
############################
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_done}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_done}]

# LVDS Rx Constraints
####################

# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 1.396> [get_ports {clk}]
# set_clock_latency -source -hold <board_min + 0.698> [get_ports {clk}]
