
# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2023.2.307
# Date: 2024-09-23 10:36

# Copyright (C) 2013 - 2023 Efinix Inc. All rights reserved.

# Device: T120F324
# Project: t120f324_lpddr3_x16
# Timing Model: C3 (final)

# PLL Constraints
#################
create_clock -period 2.5000 br0_pll_CLKOUT0
create_clock -period 32.0000 axi_clk

# GPIO Constraints
####################

# LVDS RX GPIO Constraints
############################
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {check_rstn}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {check_rstn}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {ddr_rstn}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {ddr_rstn}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {done}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {done}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {pass}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {pass}]

# LVDS Rx Constraints
####################

# LVDS TX GPIO Constraints
############################
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_br0_pll_locked}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_br0_pll_locked}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_br1_pll_locked}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_br1_pll_locked}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {pll_locked}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {pll_locked}]

# LVDS Tx Constraints
####################

# JTAG Constraints
####################
# create_clock -period <USER_PERIOD> [get_ports {bscan_TCK}]
set_output_delay -clock bscan_TCK -max 0.144 [get_ports {bscan_TDO}]
set_output_delay -clock bscan_TCK -min -0.053 [get_ports {bscan_TDO}]
set_input_delay -clock_fall -clock bscan_TCK -max 0.347 [get_ports {bscan_CAPTURE}]
set_input_delay -clock_fall -clock bscan_TCK -min 0.134 [get_ports {bscan_CAPTURE}]
set_input_delay -clock_fall -clock bscan_TCK -max 0.347 [get_ports {bscan_RESET}]
set_input_delay -clock_fall -clock bscan_TCK -min 0.134 [get_ports {bscan_RESET}]
set_input_delay -clock_fall -clock bscan_TCK -max 0.300 [get_ports {bscan_SEL}]
set_input_delay -clock_fall -clock bscan_TCK -min 0.116 [get_ports {bscan_SEL}]
set_input_delay -clock_fall -clock bscan_TCK -max 0.347 [get_ports {bscan_UPDATE}]
set_input_delay -clock_fall -clock bscan_TCK -min 0.134 [get_ports {bscan_UPDATE}]
set_input_delay -clock_fall -clock bscan_TCK -max 0.417 [get_ports {bscan_SHIFT}]
set_input_delay -clock_fall -clock bscan_TCK -min 0.161 [get_ports {bscan_SHIFT}]
# JTAG Constraints (extra... not used by current Efinity debug tools)
# create_clock -period <USER_PERIOD> [get_ports {bscan_DRCK}]
# set_input_delay -clock_fall -clock bscan_TCK -max 0.347 [get_ports {bscan_RUNTEST}]
# set_input_delay -clock_fall -clock bscan_TCK -min 0.134 [get_ports {bscan_RUNTEST}]
# Create separate clock groups for JTAG clocks. Remove DRCK clock from the list below if it is not defined.
# set_clock_groups -asynchronous -group {bscan_TCK bscan_DRCK}

# DDR Constraints
#####################
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {aaddr_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {aaddr_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {aburst_0[1] aburst_0[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {aburst_0[1] aburst_0[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {aid_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {aid_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {alen_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {alen_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {alock_0[1] alock_0[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {alock_0[1] alock_0[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {asize_0[2] asize_0[1] asize_0[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {asize_0[2] asize_0[1] asize_0[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {atype_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {atype_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {avalid_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {avalid_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {bready_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {bready_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {rready_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {rready_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {wdata_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {wdata_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {wid_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {wid_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {wlast_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {wlast_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {wstrb_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {wstrb_0[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.250 [get_ports {wvalid_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min -0.400 [get_ports {wvalid_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.900 [get_ports {aready_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min 1.500 [get_ports {aready_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.900 [get_ports {bid_0[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min 1.500 [get_ports {bid_0[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.900 [get_ports {bvalid_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min 1.500 [get_ports {bvalid_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.900 [get_ports {rdata_0[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min 1.500 [get_ports {rdata_0[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.900 [get_ports {rid_0[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min 1.500 [get_ports {rid_0[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.900 [get_ports {rlast_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min 1.500 [get_ports {rlast_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.900 [get_ports {rresp_0[1] rresp_0[0]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min 1.500 [get_ports {rresp_0[1] rresp_0[0]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.900 [get_ports {rvalid_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min 1.500 [get_ports {rvalid_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -max 3.900 [get_ports {wready_0}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~166}] -min 1.500 [get_ports {wready_0}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {aaddr_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {aaddr_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {aburst_1[1] aburst_1[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {aburst_1[1] aburst_1[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {aid_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {aid_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {alen_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {alen_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {alock_1[1] alock_1[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {alock_1[1] alock_1[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {asize_1[2] asize_1[1] asize_1[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {asize_1[2] asize_1[1] asize_1[0]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {atype_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {atype_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {avalid_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {avalid_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {bready_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {bready_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {rready_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {rready_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {wdata_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {wdata_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {wid_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {wid_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {wlast_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {wlast_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {wstrb_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {wstrb_1[*]}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.250 [get_ports {wvalid_1}]
set_output_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min -0.400 [get_ports {wvalid_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.900 [get_ports {aready_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min 1.500 [get_ports {aready_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.900 [get_ports {bid_1[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min 1.500 [get_ports {bid_1[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.900 [get_ports {bvalid_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min 1.500 [get_ports {bvalid_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.900 [get_ports {rdata_1[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min 1.500 [get_ports {rdata_1[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.900 [get_ports {rid_1[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min 1.500 [get_ports {rid_1[*]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.900 [get_ports {rlast_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min 1.500 [get_ports {rlast_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.900 [get_ports {rresp_1[1] rresp_1[0]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min 1.500 [get_ports {rresp_1[1] rresp_1[0]}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.900 [get_ports {rvalid_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min 1.500 [get_ports {rvalid_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -max 3.900 [get_ports {wready_1}]
set_input_delay -clock axi_clk -reference_pin [get_ports {axi_clk~CLKOUT~337~282}] -min 1.500 [get_ports {wready_1}]

# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 1.919> [get_ports {br0_pll_CLKOUT0}]
# set_clock_latency -source -hold <board_min + 0.738> [get_ports {br0_pll_CLKOUT0}]
# set_clock_latency -source -setup <board_max + 1.919> [get_ports {axi_clk}]
# set_clock_latency -source -hold <board_min + 0.738> [get_ports {axi_clk}]
